# Generated by Django 5.1 on 2024-08-23 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(blank=True, null=True)),
                ('chunks_total', models.IntegerField()),
                ('chunks_received', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('data', models.BinaryField()),
                ('file_upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='upload.fileupload')),
            ],
            options={
                'unique_together': {('file_upload', 'chunk_number')},
            },
        ),
    ]
